### PR TITLE
Fix the usage of `AbortSignal` across the library

### LINKED ISSUE #100: The `request` function makes no use of the received signal
**Describe the bug**
See https://github.com/dusk-network/dusk-wallet-js/blob/main/src/node.js#L238

The function receives an [abort signal](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal) as optional parameter, but then the parameter isn't used for the `fetch` call.

### PR DESCRIPTION
**Pull request by ZER0**
- Add test for checking abort during syncprogress
- Add test for checking abort during sync's fetch
- Add `mockOptions.controller` to abort during sync's fetch
-  Change block heights checks in "syncprogress more than chunkSize notes" test
- Change `getOwnedNotes` to accept progress' options instead of just `onprogress`
- Change `call_raw` and `call` to accept a `signal` as optional last param
- Change `request` to accept a `signal` as optional last param to proxy to `fetch` #100
- Fix typo in `abortable` function  (`rejected` in `reject`) #101
- Fix `clearDB` to remove `blockHeight` from `localStorage` too

Resolves #100, #101

### CODE REVIEW

File: src/wasm.js [hunk 1]
```diff
@@ -79,4 +79,4 @@ export const call_raw = (wasm, args, function_name) =>
     const dest = await memcpy(null, result.ptr, result.length);
     await free_mem(result.ptr, result.length);
     return dest;
-  })();
+  })({ signal });
```
Comment (Daksh14) [inline src/wasm.js:82]: What's this doing? I'm confused by what function are we calling here

File: tests/balance_test.js [hunk 2]
```diff
@@ -358,25 +358,107 @@ Deno.test({
...
+
+    const controller = new AbortController();
+    const { signal } = controller;
+
+    let synced = false;
+    let onBlockCalls = 0;
+
+    const from = 0;
+    const onblock = () => {
+      if (++onBlockCalls > 2) {
```
Comment (Daksh14) [inline tests/balance_test.js:375]: Nitpick: Can we make this a little more verbose because seems like we're incrementing and comparing at the same time a little confusing

**Review by Daksh14 — APPROVED** [review]
A nitpick and question no blocker for the pr everything else LGTM

File: src/wasm.js (hunk 1 above)
Comment (ZER0) [reply src/wasm.js:82]: This is `exu`. It's calling the `task` resulting by executing `wasm.task`: exu already had the capability to abort a task using a signal. It just need to receive it.

File: tests/balance_test.js (hunk 2 above)
Comment (ZER0) [reply tests/balance_test.js:375]: This is the (prefix increment operator)[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Increment] and it's intended use is exactly that one: it increment first, and then comparing the new value. While the postfix would have incremented the value, but comparing the previous one. Does not exists in rust, and that's why you might be confused by its use, however it exists in most of the other languages such C, Java, etc.
